### ISSUE TITLE
ImportError: cannot import name 'Citation'

### ISSUE THREAD

**Issue by sturne29** [statdivlab/q2-corncob#8]
Tried to install the qiime2 corncob plugin following the instructions in the community tutorial, but when I try to run the refresh-cache command, I get an "ImportError: cannot import name 'Citation'". Is this an issue on my end, or is a file missing from the repository, or is something else going on?

Thank you!

**Comment by paulinetrinh** [comment]
@sturne29 Happy to troubleshoot this with you! Can you provide me with the qiime2 version that you're running? Also when you run `qiime corncob --citations` what happens?

**Comment by sturne29** [comment]
I'm running qiime2-2018.8, which I think is the newest version. 

When I run `qiime corncob --citations` I get the same error. In fact, running any qiime command gives me the same error, so I can't do much with that particular conda environment. I actually ended up making a second one so I could continue using qiime2 as usual. 

Here's a more complete version of the error, which as far as I can tell is identical every time.

>   File "/Users/sturne29/miniconda3/envs/qiime2-2018.8/lib/python3.5/site-packages/q2_corncob/plugin_setup.py", line 11, in <module>
    from qiime2.plugin import (Plugin, Str, Properties, Choices, Int, Bool, Range, Float, Set, Visualization, Metadata, MetadataColumn, Categorical, Numeric, Citation, SemanticType)
ImportError: cannot import name 'Citation'

**Comment by paulinetrinh** [comment]
@sturne29 Okay! that should be fixed now. Typo error. Let me know if that fixed it for you.

**Comment by sturne29** [comment]
Looks like things are working as expected now! Thank you!
